### ISSUE TITLE
URL query string with array value is failing

### ISSUE THREAD

**Issue by AgrPriyank** [pkemp/arangodb-query-parser#10]
@pkemp , The latest changes in version 0.1.15 has a bug which doesn't update the result.filter with the IN query but updates the bindVars. This is resulting in AQL syntax error. I've left a comment on the commit where the filter needs to be updated. Can you fix it release a new version?

**Comment by pkemp** [comment]
Thanks @AgrPriyank this is now fixed in version 0.1.18.
