### ISSUE TITLE
Default operator results in AQL syntax

### ISSUE THREAD

**Issue by AgrPriyank** [pkemp/arangodb-query-parser#11]
In case a filter is passed with just a key and without any value, the default operator is selected as '!'. 
When translated to actual AQL syntax, the query becomes, FILTER doc.attribute ! @value, where value is empty string. This syntax is not a valid AQL query. 
@pkemp , wouldn't having '==' as default operator make more sense?

https://github.com/pkemp/arangodb-query-parser/blob/674f93b1e0188e36d5a3cee4c4baef1383ba9ea3/src/index.ts#L294-L318

**Comment by pkemp** [comment]
@AgrPriyank I agree, this has now been changed in 0.1.19.
