### ISSUE TITLE
Fails to filter with dot notation for nested objects

### ISSUE THREAD

**Issue by poojaribhaskar** [pkemp/arangodb-query-parser#2]
Consider an example:
FOR o IN documents FILTER o.topLevel.secondLevel == @value RETURN o

This will work, when provided with bind values.

But the parser generates as below, where the key is also used in bind with a dot and it would not work.
FOR o IN documents FILTER o.topLevel.secondLevel == @topLevel.secondLevel RETURN o

**Comment by pkemp** [comment]
Hi @poojaribhaskar, This is fixed now in version 0.1.9, thanks for the report!

**Comment by poojaribhaskar** [comment]
Thanks, appreciate it. But, apparently it works only with single nested scenario.

Consider the nested key as "me.you.who", then after key.repalce (".", "_") it is revised as "me_you.who" where the dot is replaced only in the first occurrence.

**Comment by pkemp** [comment]
@poojaribhaskar you're right, this is fixed now in version 0.1.11.

**Comment by poojaribhaskar** [comment]
Thanks!
