### ISSUE TITLE
Does not return if fields is a property in object

### ISSUE THREAD

**Issue by poojaribhaskar** [pkemp/arangodb-query-parser#3]
Consider an Object as below.
{
"name": "me",
"fields": ["him","her"]
}

If the query is framed as ?fields=name,fields then the return will include name but not fields

**Comment by pkemp** [comment]
Hi @poojaribhaskar, if you have properties with the same name I would suggest to use the fieldsKey option to change the URL parameter name from fields to something else:

```javascript
const parser = new ArangoDbQueryParser({ collection: 'documents', fieldsKey: '_fields' });
const parsed = parser.parse('_fields=name,fields');
const query = parser.createQuery(parsed);
assert.equal(query, 'FOR o IN documents RETURN { name: o.name, fields: o.fields }');
```
