### ISSUE TITLE
Range filters are not working

### ISSUE THREAD

**Issue by sudhish-ps** [pkemp/arangodb-query-parser#4]
When the query is having filter criteria for an attribute value with operators like >,<,>=,<= is not providing proper result.
For e.g. query with condition like createdDate>=2020-09-01&createdDate<=2020-09-20 the result is not retrieving properly.
The bindVar produced is only one in this case like o.updatedAt <= @updatedAt AND o.updatedAt >= @updatedAt.
This cases need to be handled in priority.

**Comment by pkemp** [comment]
Thanks this has now been fixed in version 0.1.13.
