### ISSUE TITLE
Binding variable value for _key field is not parsing correctly

### ISSUE THREAD

**Issue by sudhish-ps** [pkemp/arangodb-query-parser#5]
There are certain situation in collections the auto generated key of _key has only numeric like as below
{
id:flows/681620
_rev:_bVlGnGu---
_key:681620
}
In this case if we are sending filter query for _key as @key the AQL looks like o._key == 681620 and the ArangoDB is not fetching any value. But in such cases if we pass it as o._key == "681620" the result is fetching.

So the issue is only for _key having numeric data, if it is alphanumeric no issue.
This need an urgent look seems to be having high impact.

**Comment by pkemp** [comment]
@sudhish-ps 

In such case you can use the built-in string caster in the URL:

?_key=string(681620)
