### ISSUE TITLE
Querying array type attribute is not supporting

### ISSUE THREAD

**Issue by sudhish-ps** [pkemp/arangodb-query-parser#6]
The AQL query is not generating properly for the filter condition with array type attribute.
For e.g. the below document has array attribute with multiple data
{
"paytype": "wage",
"employeeIds":["e1","e2","e3","e4","e5"]
}

if we pass query string as  ?employeeids=e1, then the query generated is like below
FOR o IN paylist FILTER  o.employeeIds == @employeeIds RETURN o

But the expected query for such attributes is
FOR o IN paylist FILTER  o.employeeIds ANY == @employeeIds RETURN o

For such result generation we need a way to inform the parser attribute is of type array, and the query generated should have comparison operator of type ANY/ALL/NONE 'operator'

Any existing solution for this.

**Comment by pkemp** [comment]
I added new array operators to release 0.1.14:

?employeesids?=e1  -> ANY
?employeesids*=e1  -> ALL
?employeesids#=e1  -> NONE
