### ISSUE TITLE
Regular expression with delimiter is not working

### ISSUE THREAD

**Issue by sudhish-ps** [pkemp/arangodb-query-parser#7]
The URL with query string for retrieving the documents which has name specified below;
__Dataset__:
{
"name":"test-PP",
"email":"abcd@xyz.com"
}
Query: https://localhost/Employee/name=/test-pp/i

The AQL generated for above request is 
FOR doc IN employee
FILTER doc.name =~ /test-PP/i
RETURN doc

This query is not returning any result b'coz AQL does not use delimiters for Regexes like Perl or sed do, just regular strings.
Also, if we change the filter to 'test-PP/i' or 'test-PP' the result is not fetching due to comparison fails.

So for such regular expression filter the recommended query to be generated should be like below;
FOR doc IN employee
FILTER REGEX_TEST(doc.name, "test-PP", true)
RETURN doc

Reference https://github.com/arangodb/arangodb/issues/13012

Please add feature to generate such query for regular expression.

**Comment by pkemp** [comment]
The regular expression filters are fixed now in release 0.1.15.
