### ISSUE TITLE
OR statement in URL query string

### ISSUE THREAD

**Issue by sudhish-ps** [pkemp/arangodb-query-parser#8]
Need to support OR statement in REST API, and to build right query string for that.
In some business case we have to filter the document with OR condition like below for e.g.;

FOR doc IN employee
Filter doc.position == 'Manager' OR doc.age >= 50
return doc

How to generate such queries with the parser and how to define such condition in query string ?.
Currently multiple query parameters specified in the query string is generating AQL with AND condition only, but definitely there is need of OR also.

**Comment by pkemp** [comment]
I added basic support in release 0.1.17 for OR in filters, just add exclamation mark as the prefix for the field name. Example:

?position=Manager&!age>=50

**Comment by sudhish-ps** [comment]
@pkemp ,

Instead of ! operator can we use exact | operator to distinguish the OR condition. B'coz the ! gives a confusion of its meaning, just a concern.

**Comment by pkemp** [comment]
@sudhish-ps good point, I changed the operator in 0.1.19 to |.
